### ISSUE TITLE
JS modification of <input> attributes

### ISSUE THREAD

**Issue by Calefornia** [duckduckgo/duckduckgo-styles#22]
Hi! After a little digging, I might have a solution. It involves updating the default input attributes and deleting two lines of JS.

Currently, the search bar's input attributes look like this:
`<input class="query" type="text" size="40" name="q" autocomplete="off" value="" autofocus="">`

These are modified by [d1886.js](https://duckduckgo.com/d1886.js), as follows:
`this.$input[0].setAttribute("autocapitalize", "off");`
`this.$input[0].setAttribute("autocorrect", "off");`

Without turning those two things off, my phone's keyboard offers suggestions and fights me on spelling, which is quite obnoxious. As the [HTML](https://duckduckgo.com/html) and [Lite](https://duckduckgo.com/lite) versions of DDG have no way to modify their attributes, it seems that relying on JS is problematic.

I don't want to break anything, but I think we would be fine removing those two functions. Adding `autocorrect="off"` and `autocapitalize="off"` to the default input attributes should make everything go smoothly.

**Comment by andrey-p** [comment]
Hey @Calefornia, thanks for reporting this. Yeah, you're right, we want to keep the experience similar between the main page and HTML/Lite. I'll have a look.

**Comment by Calefornia** [comment]
Awesome, thank you! I'm using the standard iOS keyboard if that helps at all

**Comment by Calefornia** [comment]
I just checked again, and everything is working fine, so perhaps this is the result of a software update on my end. Apple might have done some keyboard tweaking. However, I'm still suspicious of using the setAttribute things above. I'm sure someone knows their purpose, and it's not really a big deal one way or the other. But since it's working fine for me, maybe you don't need to make any changes. The html and lite versions are good. It's possible they would misbehave on earlier versions of iOS, but I have no easy way of making that determination. Take care!
