### ISSUE TITLE
Is this the style used on duckduckgo.com?

### ISSUE THREAD

**Issue by casertap** [duckduckgo/duckduckgo-styles#26]
I love the minimal approach to style the search result of duckduckgo.com.

The classes used on the page duckduckgo.com does not match the one defined on this project.

Same thing for the layout defined by litestrap eg. (.whole, .half, .third, .twothird, .twothirds, .quarter, .threequarter, .threequarters, .sixth, .eighth, .ninety, .eighty, .seventy, .sixty, .fifty, .forty, .thirty, .twenty, .ten) duckduckgo.com does not seem to use them.

Where is duckduckgo-styles used ? 
Is the css of the main duckduckgo.com css available ?

**Comment by andrey-p** [comment]
Hey @casertap, we've got quite a few more CSS styles in our internal repos. This repo contains some basic styles (colours, mixins, etc) that we can reuse on the Community Platform, which is completely open source.

I'm afraid we won't be making the rest available for some time.
