### ISSUE TITLE
(BUG) Unreadable Fonts on Windows 10

### ISSUE THREAD

**Issue by TheAresjej** [duckduckgo/duckduckgo-styles#55]
Current font is unreadable 😞

**2018**
![2018](https://i.imgur.com/G8MMffZ.png)

**2019**
![2019](https://i.imgur.com/uNuQA7h.png)

OS: Windows 10 (1809)
OS Language: English UK
Browser Language: English UK

**Comment by TheAresjej** [comment]
more: https://twitter.com/TheAresjej/status/1101613283101077508

**Comment by moollaza** [comment]
@TheAresjej thanks for reporting. 

What browser are you using? Are you using the default settings or do you have custom settings set? Can you confirm if the font is the default Proxima Nova we use, or something else?

We recently darkened some colours and increased the font size to improve contrast and readability so this may be related.

**Comment by TheAresjej** [comment]
Brave Browser: Version 0.60.47 Chromium: 72.0.3626.119
I restarted the settings so all fonts are on default (Proxima Nova / Large / Normal).
Photos are taken from a private card so no settings other than language should be loaded.

You can also change this illegible font 😜
Default:
![img](https://i.imgur.com/rYKUm9C.png)
Edit: 
![img](https://i.imgur.com/ufHD1MZ.png)

"Muli", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"

**Comment by moollaza** [comment]
@TheAresjej thanks for the details. From my testing it seems like Brave renders our default ProximaNova font noticeably thinner than FF, Chrome, Edge on Windows 10 and I'm not sure why.

Overall, our font doesn't look as great on Windows as it appear on Macs. We're discussing this internally to determine next steps but for now it might be best for you to choose a different font via the settings. As you mentioned we may ultimately need to use system or another font on Windows.

**Comment by TheAresjej** [comment]
Brave: Version 0.61.51 Chromium: 73.0.3683.75 - FIXED! 👍
